steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-model', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-model']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s-deployment.yaml'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s-service.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_REGION=asia-southeast2'
    - 'CLOUDSDK_CONTAINER_CLUSTER=AI-Cluster'
images:
- 'gcr.io/$PROJECT_ID/ai-model'
