options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-model', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-model']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'get-credentials'
    - 'AI-Cluster'
    - '--region=asia-southeast2'
    - '--project=$PROJECT_ID'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s-deployment.yaml'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s-service.yaml'

images:
- 'gcr.io/$PROJECT_ID/ai-model'
